configName: 9x60
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: SAM9X60
projectName: ''
settings:
  PackageFilter: audio;bsp;core;csp;Devices;dev_packs;gfx;harmony-services;mc_apps_pic32cm_mc;mc_apps_pic32mk;mc_apps_sam_c2x;mc_apps_sam_d5x_e5x;mc_apps_sam_e7x_s7x_v7x;mc_apps_sam_rh707;mc_apps_sam_rh71;motor_control;quick_docs;tflite-micro-apps;touch;usb;wireless_apps_pic32cxbz2_wbz45;wireless_pic32cxbz_wbz;wireless_system_pic32cxbz_wbz;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.7.85\atdf\SAM9X60.atdf
