format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_canvas}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DisplayDriverName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_canvas, value: lcdcDisplayDriver}
  - type: Menu
    attributes: {id: rtosMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_canvas}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver}
  - type: DirectDependency
    attributes: {id: gfx_display_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_lcdc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: le_gfx_driver_lcdc}
- type: ElementPosition
  attributes: {x: '610', y: '260', id: gfx_canvas}
