format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_gfx2d}
children:
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: GFX2D}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: plib_gfx2d}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: GFX2D}
  - type: DirectCapability
    attributes: {id: LE GPU Driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gpu_driver}
- type: ElementPosition
  attributes: {x: '408', y: '414', id: le_gfx_gfx2d}
